### ISSUE TITLE
TypeError: Cannot read property 'getScriptTree' of null

### ISSUE THREAD

**Issue by SpookOz** [ryanblenis/MeshCentral-ScriptTask#52]
Hi Ryan. I think the latest update of MC may have broken your plugins. I'm getting a "TypeError: Cannot read property" on all of them. Here is the one for ScriptTask:

TypeError: Cannot read property 'getScriptTree' of null
    at Object.obj.handleAdminReq (/home/luke/meshcentral-data/plugins/scripttask/scripttask.js:224:20)
    at Object.obj.handleAdminReq (/home/luke/node_modules/meshcentral/pluginHandler.js:527:40)
    at obj.handlePluginAdminReq (/home/luke/node_modules/meshcentral/webserver.js:6174:34)
    at Layer.handle [as handle_request] (/home/luke/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/luke/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/home/luke/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/home/luke/node_modules/express/lib/router/layer.js:95:5)
    at /home/luke/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/luke/node_modules/express/lib/router/index.js:346:12)
    at next (/home/luke/node_modules/express/lib/router/index.js:280:10)
    at /home/luke/node_modules/meshcentral/webserver.js:6514:20
    at Layer.handle [as handle_request] (/home/luke/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/luke/node_modules/express/lib/router/index.js:328:13)
    at /home/luke/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/luke/node_modules/express/lib/router/index.js:346:12)
    at next (/home/luke/node_modules/express/lib/router/index.js:280:10)

Do you know what might be causing this?

Thanks!

**Comment by pierrecorsini** [comment]
Dupe of #47

**Comment by pierrecorsini** [comment]
I have tried to freeze a repo on version 0.0.18 and see if this works.
This doesn't.

Apparently MC's recent updates broke this repo.

**Comment by SpookOz** [comment]
Hi @pierrecorsini . Thanks sorry. I did see that issue but thought it was different as mine seemed to break with the latest update (1.1.35)

**Comment by si458** [comment]
i believe my PR https://github.com/ryanblenis/MeshCentral-ScriptTask/pull/53 should fix the issue if you wanted to try it

**Comment by SpookOz** [comment]
It worked! Thanks so much!

**Comment by ryanblenis** [comment]
Thanks for the fix PR, pushed up and increased version numbers. Hope that fixes everyone!
